#  **EXAM FOR PYTHON**

## Q.1: Sum and average of first n natural numbers

### 1. Sum and average of n numbers in Python

### 2. Accept the number n from a user
### 3. Use input() function to accept integer number from a user.

### 4. Run a loop till the entered number
Next, run a for loop till the entered number using the range() function. In each iteration, we will get the next number till the loop reaches the last number, i.e., n.

### 5. Calculate the sum
In each iteration, keep adding the current number into the sum variable to calculate the addition. Use a formula sum = sum + current number.

### 6. Calculate the average
At last, after the loop ends, calculate the average using a formula average = sum / n. Here, The n is a number entered by the user.


### Desired Output


Enter number 10

Sum of first  10 numbers is:  55

Average of  10 numbers is:  5.5

## Q.2: Check if the first and last numbers of a list are the same
Write a code to return True if the list’s first and last numbers are the same. If the numbers are different, return False.

### Given:

numbers_x = [10, 20, 30, 40, 10]

numbers_y = [75, 65, 35, 75, 30]

### Expected Output:

Given list: [10, 20, 30, 40, 10]

result is True


numbers_y = [75, 65, 35, 75, 30]

result is False

## Q.3: Check Palindrome Number
Write a Python code to check if the given number is palindrome. A palindrome number is a number that is the same after reverse. 
**For example, 545 is the palindrome number.**

### Expected Output:
original number 121

Yes. given number is palindrome number

original number 125

No. given number is not palindrome number

## Q.4: Create an inner function to calculate the addition in the following way
**Create an outer function that will accept two parameters, a and b**

**Create an inner function inside an outer function that will calculate the addition of a and b**

**At last, an outer function will add 5 into addition and return it**
### Given:
result = outer_fun(5, 10)
### Output:
20

## Q.5: Print a date in a the following format
**Day_name      Day_number      Month_name      Year**

#### Refer: Python DateTime Format Using Strftime()

### Given:
given_date = datetime(2020, 2, 25)

### Expected output:
Tuesday 25 February 2020

## Q.6: Calculate number of days between two given dates
### Given:

date_1 = datetime(2020, 2, 25)

date_2 = datetime(2020, 9, 17)

### Expected output:
**205 days**

## Q.7: Turn every item of a list into its square
Given a list of numbers. write a program to turn every item of a list into its square.

### Given:
numbers = [1, 2, 3, 4, 5, 6, 7]

### Expected output:
[1, 4, 9, 16, 25, 36, 49]

## Q.8: Add new item to list after a specified item
Write a program to add item 7000 after 6000 in the following Python List

### Given:
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
### Expected output:
[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]

## Q.9: Calculate the cube of all numbers from 1 to a given number
Write a Python program to print the cube of all numbers from 1 to a given number

### Given:

**input_number = 6** // Take user input

### Expected output:

Current Number is : 1  and the cube is 1

Current Number is : 2  and the cube is 8

Current Number is : 3  and the cube is 27

Current Number is : 4  and the cube is 64

Current Number is : 5  and the cube is 125

Current Number is : 6  and the cube is 216

## Q.10: Write all content of a given file into a new file by skipping line number 5
### Hints:
Python file handling

Python Read file

Python write file

Create a test.txt file and add the below content to it.

### Given test.txt file:

line1

line2

line3

line4

line5

line6

line7
### Expected Output: new_file.txt

line1

line2

line3

line4

line6

line7

## Q.11: Assign a different name to function and call it through the new name
Below is the function **display_student(name, age)**. Assign a new name **show_student(name, age)** to it and call it using the new name.

### Given:
def display_student(name, age):
    print(name, age)

**display_student("Emma", 26)**
### Expected output
You should be able to call the same function using

**show_student(name, age)**

## Q.12: Change value of a key in a nested dictionary
Write a Python program to change Brad’s salary to 8500 in the following dictionary.

### Given:

sample_dict = {

    'emp1': {'name': 'Jhon', 'salary': 7500},
    
    'emp2': {'name': 'Emma', 'salary': 8000},
    
    'emp3': {'name': 'Brad', 'salary': 500}
    
}
### Expected output:

{

   'emp1': {'name': 'Jhon', 'salary': 7500},
   
   'emp2': {'name': 'Emma', 'salary': 8000},
   
   'emp3': {'name': 'Brad', 'salary': 8500}
   
}

## Q.13: Define a class which has at least two methods:
### getString: to get a string from console input
### printString: to print the string in upper case.
### Also please include simple test function to test the class methods.

### Hints:
*Use __ init __ method to construct some parameters*

## Q.14: Create a child class Bus that will inherit all of the variables and methods of the Vehicle class
### Given:
#### class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage

### Create a Bus object that will inherit all of the variables and methods of the parent Vehicle class and display it.

### Expected Output:

**Vehicle Name: School Volvo Speed: 180 Mileage: 12**

## Q.15: Student management system in Python

**Problem Statement: Write a program to build a simple Student Management System using Python which can perform the following operations:**
1. Accept
2. Display
3. Search
4. Delete
5. Update

### Prerequisite: **Classes and objects in python**

### Desired Output

Operations used, 

1.Accept Student details

2.Display Student Details

3.Search Details of a Student

4.Delete Details of Student

5.Update Student Details

6.Exit


_______________________________________________


List of Students

Name :  A

RollNo :  1

Marks1 :  100

Marks2 :  100


_______________________________________________


Name :  B

RollNo :  2

Marks1 :  90

Marks2 :  90

_______________________________________________


Name :  C

RollNo :  3

Marks1 :  80

Marks2 :  80


_______________________________________________


 Student Found, 
 
Name :  B

RollNo :  2

Marks1 :  90

Marks2 :  90

_______________________________________________


2

List after deletion

Name :  A

RollNo :  1

Marks1 :  100

Marks2 :  100

_______________________________________________


Name :  C

RollNo :  3

Marks1 :  80

Marks2 :  80

_______________________________________________


2

List after updation

Name :  A

RollNo :  1

Marks1 :  100

Marks2 :  100

_______________________________________________


Name :  C

RollNo :  2

Marks1 :  80

Marks2 :  80

_______________________________________________


Thank You !

## Best of Luck...